### ISSUE TITLE
Linker error on recent Ubuntu with gcc 9.2.1

### ISSUE THREAD

**Issue by lskh** [kensanata/mkhexgrid#1]
to compile successfully on recent Ubuntu with gcc 9.2.1 LDFLAGS needs to be changed to LDLIBS in Makefile:

```
13c13
< LDFLAGS=-lm -lstdc++ -lgd
---
> LDLIBS=-lm -lstdc++ -lgd
```
Found the solution on this fork:

https://github.com/mtngrown/mkhexgrid/blob/master/Makefile

**Comment by kensanata** [comment]
Hm, bei mir funktioniert's mit dem bestehenden Code, aber ich verwende auch gcc (Debian 8.3.0-6) 8.3.0. Da es mit der Änderung aber genauso gut klappt, kann man das ja schnell einbauen.

```
~/src/mkhexgrid $ make
g++  -c -g -O2 -W -Wall -DVERSION='"0.1.1"'  -c -o mkhexgrid.o mkhexgrid.cpp
g++  -c -g -O2 -W -Wall -DVERSION='"0.1.1"'  -c -o grid.o grid.cpp
g++  -c -g -O2 -W -Wall -DVERSION='"0.1.1"'  -c -o png.o png.cpp
g++  -c -g -O2 -W -Wall -DVERSION='"0.1.1"'  -c -o ps.o ps.cpp
g++  -c -g -O2 -W -Wall -DVERSION='"0.1.1"'  -c -o svg.o svg.cpp
g++ -lm -lstdc++ -lgd  mkhexgrid.o grid.o png.o ps.o svg.o   -o mkhexgrid
```

**Comment by kensanata** [comment]
Fixed in c571074.
